### ISSUE TITLE
node 0.10

### ISSUE THREAD

**Issue by uakfdotb** [fzaninotto/uptime#127]
uptime doesn't seem to be working with node.js v0.10 anymore:

$ node app.js
Monitor origin started
Warning: connection.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
Warning: connection.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
   info  - socket.io started
Express server listening on port 8082 in production mode
[Error: http://user:password@localhost:8082/api/checks/needingPoll resource responded with error code: 404]

http.js:708
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:708:11)
    at ServerResponse.res.setHeader (/home/username/uptime/node_modules/express/node_modules/connect/lib/patch.js:59:22)
    at next (/home/username/uptime/node_modules/express/node_modules/connect/lib/proto.js:153:13)
    at Function.app.handle (/home/username/uptime/node_modules/express/node_modules/connect/lib/proto.js:198:3)
    at Server.app (/home/username/uptime/node_modules/express/node_modules/connect/lib/connect.js:66:31)
    at Manager.handleRequest (/home/username/uptime/node_modules/socket.io/lib/manager.js:564:28)
    at Server.<anonymous> (/home/username/uptime/node_modules/socket.io/lib/manager.js:118:10)
    at Server.EventEmitter.emit (events.js:117:20)
    at HTTPParser.parser.onIncoming (http.js:2014:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete](http.js:119:23)

$ node -v
v0.10.0

**Comment by kishn** [comment]
for MongoError: unauthorized 
I have used  - connectionString:     mongodb://localhost/uptime
It's Working.
