### ISSUE TITLE
raw-socket@1.2.2 Failed to install

### ISSUE THREAD

**Issue by DonRichards** [fzaninotto/uptime#238]
npm install gave an error. This is the full stack. Is there a way around this? 

```
$ sudo npm install
npm http GET https://registry.npmjs.org/net-ping/1.1.7
npm http 304 https://registry.npmjs.org/net-ping/1.1.7
npm http GET https://registry.npmjs.org/raw-socket
npm http 304 https://registry.npmjs.org/raw-socket

> raw-socket@1.2.2 install /var/www/uptime/node_modules/net-ping/node_modules/raw-socket
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead
gyp ERR! stack     at install (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:66:16)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at getNodeDir (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:152:20)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:95:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:719:7)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:110:17)
gyp ERR! stack     at maybeClose (child_process.js:991:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:1141:11)
gyp ERR! stack     at Socket.EventEmitter.emit (events.js:107:17)
gyp ERR! stack     at Pipe.close (net.js:461:12)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/uptime/node_modules/net-ping/node_modules/raw-socket
gyp ERR! node -v v0.11.13-pre
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
npm ERR! raw-socket@1.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the raw-socket@1.2.2 install script.
npm ERR! This is most likely a problem with the raw-socket package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls raw-socket
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /var/www/uptime
npm ERR! node -v v0.11.13-pre
npm ERR! npm -v 1.4.6
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/uptime/npm-debug.log
npm ERR! not ok code 0
```

**Comment by johnjelinek** [comment]
Even number install fails too:
```
$ node -v
v0.12.0
```

```
raw.target.mk:84: recipe for target 'Release/obj.target/raw/src/raw.o' failed
make: *** [Release/obj.target/raw/src/raw.o] Error 1
make: Leaving directory '/src/node_modules/net-ping/node_modules/raw-socket/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.13.0-32-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /src/node_modules/net-ping/node_modules/raw-socket
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.0
npm ERR! code ELIFECYCLE

npm ERR! raw-socket@1.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the raw-socket@1.2.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the raw-socket package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls raw-socket
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /src/npm-debug.log
```

**Comment by johnjelinek** [comment]
works on `v0.10.36` though.

**Comment by i-sam** [comment]
yep, got the same problem on the 0.12.0

**Comment by drj-io** [comment]
Same.

**Comment by DonRichards** [comment]
I ultimately had to reinstall Node.js

**Comment by leoh** [comment]
Got the same issue at 0.12.1, 0.12.4 ! worked at 0.10

**Comment by chancesmith** [comment]
Node v4.2.1 worked for me

**Comment by chancesmith** [comment]
Confirm 0.12.4

I went in and changed the package.json node version

**Comment by DonRichards** [comment]
This is 8 years open. Likely no longer relevant.
