### ISSUE TITLE
Error when running application Uptime (throw err)

### ISSUE THREAD

**Issue by richardsonlima** [fzaninotto/uptime#251]
Hello Dears,

About 24hs after having run the application, the following error occurs,what's procedure for solve this problem? I need fix it.

/home/richardson/uptime/node_modules/mongoose/lib/utils.js:413
        throw err;
              ^
TypeError: Cannot read property 'firstTested' of null
    at IntervalBuilder.calculateDuration (/home/richardson/uptime/lib/intervalBuilder.js:100:44)
    at Array.async.auto.duration [as 3](/home/richardson/uptime/lib/intervalBuilder.js:48:14)
    at listener (/home/richardson/uptime/node_modules/async/lib/async.js:412:46)
    at /home/richardson/uptime/node_modules/async/lib/async.js:371:17
    at Array.forEach (native)
    at _forEach (/home/richardson/uptime/node_modules/async/lib/async.js:26:24)
    at taskComplete (/home/richardson/uptime/node_modules/async/lib/async.js:370:13)
    at Promise.taskCallback (/home/richardson/uptime/node_modules/async/lib/async.js:396:21)
    at Promise.<anonymous> (/home/richardson/uptime/node_modules/mongoose/node_modules/mpromise/lib/promise.js:162:8)
    at Promise.emit (events.js:95:17)

**Comment by JaySim20** [comment]
Hi - I've applied this fix and it seems to resolve the crash, but now I can't seem to add any new tags. I see this in the logs:

{ [MongoError: assertion src/mongo/db/query/planner_analysis.cpp:114] name: 'MongoError' }

Thoughts?
