### ISSUE TITLE
TypeError: Cannot read property 'firstTested' of null

### ISSUE THREAD

**Issue by liqinshan** [fzaninotto/uptime#279]
I got an error：

/opt/app/uptime-master/node_modules/mongoose/lib/utils.js:413
        throw err;
              ^
TypeError: Cannot read property 'firstTested' of null
    at IntervalBuilder.calculateDuration (/opt/app/uptime-master/lib/intervalBuilder.js:100:44)
    at Array.async.auto.duration [as 3](/opt/app/uptime-master/lib/intervalBuilder.js:48:14)
    at listener (/opt/app/uptime-master/node_modules/async/lib/async.js:412:46)
    at /opt/app/uptime-master/node_modules/async/lib/async.js:371:17
    at Array.forEach (native)
    at _forEach (/opt/app/uptime-master/node_modules/async/lib/async.js:26:24)
    at taskComplete (/opt/app/uptime-master/node_modules/async/lib/async.js:370:13)
    at Promise.taskCallback (/opt/app/uptime-master/node_modules/async/lib/async.js:396:21)
    at Promise.<anonymous> (/opt/app/uptime-master/node_modules/mongoose/node_modules/mpromise/lib/promise.js:162:8)
    at Promise.emit (events.js:95:17)

**Comment by chaseconey** [comment]
+1 I am having this same issue.

```
    /srv/uptime/node_modules/mongoose/lib/utils.js:413
        throw err;
              ^
TypeError: Cannot read property 'firstTested' of null
    at IntervalBuilder.calculateDuration (/srv/uptime/lib/intervalBuilder.js:100:44)
    at Array.async.auto.duration [as 3] (/srv/uptime/lib/intervalBuilder.js:48:14)
    at listener (/srv/uptime/node_modules/async/lib/async.js:412:46)
    at /srv/uptime/node_modules/async/lib/async.js:371:17
    at Array.forEach (native)
    at _forEach (/srv/uptime/node_modules/async/lib/async.js:26:24)
    at taskComplete (/srv/uptime/node_modules/async/lib/async.js:370:13)
    at Promise.taskCallback (/srv/uptime/node_modules/async/lib/async.js:396:21)
    at Promise.<anonymous> (/srv/uptime/node_modules/mongoose/node_modules/mpromise/lib/promise.js:162:8)
    at Promise.emit (events.js:95:17)
```

**Comment by adeslade** [comment]
I encountered the same issue after deleting a check.

I fixed it by running the following in mongo:

```
check_ids = db.checks.find({}, { _id: true }).toArray().map(function (check) { return check._id });
db.pings.remove({ check: { $nin: check_ids }});
```
