### ISSUE TITLE
Trouble with Arch Linux Install.

### ISSUE THREAD

**Issue by AustinSaintAubin** [fzaninotto/uptime#306]

**Comment by fred-snyder** [comment]
I think I have similar error. Is this because this Node.JS version is not compatible with uptime?

```
$ npm install

> raw-socket@1.4.0 install /home/sv1-admin/uptime/node_modules/raw-socket
> node-gyp rebuild

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:78:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:82:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:93:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 3.19.0-47-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/sv1-admin/uptime/node_modules/raw-socket
gyp ERR! node -v v5.5.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-uptime@3.2.0 /home/sv1-admin/uptime
├─┬ express@3.2.0
│ ├── commander@0.6.1
│ └── mkdirp@0.3.5
└─┬ webpagetest@0.2.0
  └─┬ mocha@1.13.0
    ├── commander@0.6.1
    ├── diff@1.0.7
    ├─┬ glob@3.2.3
    │ ├── graceful-fs@2.0.3
    │ ├── inherits@2.0.1
    │ └─┬ minimatch@0.2.14
    │   ├── lru-cache@2.7.3
    │   └── sigmund@1.0.1
    ├── growl@1.7.0
    └── mkdirp@0.3.5

npm ERR! Linux 3.19.0-47-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! raw-socket@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the raw-socket@1.4.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the raw-socket package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls raw-socket
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sv1-admin/uptime/npm-debug.log

```

**Comment by fred-snyder** [comment]
I tried a lot of older versions. Down to 0.10.26
I tried both these dockers:
https://github.com/ekalinin/docker-uptime
https://github.com/techtraits/docker-uptime
But every time it fails on the raw-socket
I'm on Ubuntu 14.04

**Comment by fred-snyder** [comment]
https://github.com/gunmetal313-nodejs/uptime2

This works perfectly !!
