### ISSUE TITLE
ICMP Support

### ISSUE THREAD

**Issue by petakcm8** [fzaninotto/uptime#314]
Hello, 

I came across this wonderful tool a few days ago, and I noticed the ICMP support has been removed.

I tried adding ICMP support via commit 9696271194820865307a3bfe6f3ec8c9f2485660 but after editing files in my 3.2 version I get an error related to node module:

BasePoller = require ('./base');

Error: Cannot find module './base'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/uptime/lib/pollers/icmp/icmpPoller.js:9:18)

What is this module ?

Tried to do npm install base but didn t help

Thanks

**Comment by pk-pranshu** [comment]
var BasePoller = require ('../basePoller'); 
It should be basePoller
