### ISSUE TITLE
Send Mail - Fails

### ISSUE THREAD

**Issue by DivyaYash** [fzaninotto/uptime#337]
Irrespective of what I try to configure the default.yaml with, I get the below error when uptime attempts to send mail..This crashes the uptime service.

Mongoose: checks.findOne({ _id: ObjectId("56573f59e675a62e16000007") }) { fields: undefined, safe: undefined }  
/opt/node-uptime/node_modules/mongoose/lib/utils.js:413
        throw err;
              ^
TypeError: undefined is not a function
    at Nodemailer.setGeneralOptions (/opt/node-uptime/node_modules/nodemailer/lib/nodemailer.js:238:23)
    at Nodemailer.generateMailObject (/opt/node-uptime/node_modules/nodemailer/lib/nodemailer.js:196:10)
    at Nodemailer.sendMail (/opt/node-uptime/node_modules/nodemailer/lib/nodemailer.js:184:10)
    at /opt/node-uptime/node_modules/nodemailer/lib/nodemailer.js:69:20
    at Nodemailer.validateSettings (/opt/node-uptime/node_modules/nodemailer/lib/nodemailer.js:173:5)
    at sendMail (/opt/node-uptime/node_modules/nodemailer/lib/nodemailer.js:63:12)
    at Transport.transport.sendMail (/opt/node-uptime/node_modules/nodemailer/lib/nodemailer.js:40:9)
    at Promise.<anonymous> (/opt/node-uptime/plugins/email/index.js:81:14)
    at Promise.<anonymous> (/opt/node-uptime/node_modules/mongoose/node_modules/mpromise/lib/promise.js:162:8)
    at Promise.emit (events.js:107:17)

**Comment by DivyaYash** [comment]
Issue was with the Nodemailer version. While trying multimail plugin, happen to install nodemailer@0.7, after which the default email plugin started to work!!
