### ISSUE TITLE
suport raspbian

### ISSUE THREAD

**Issue by mostafaasadi** [fzaninotto/uptime#355]
I try to install uptime on raspberrypi and raspbian but seems that debian repo deos not have minimum dependecy version 
it is so cool , uptime will run on raspberrypi 
best regards

**Comment by mostafaasadi** [comment]
```

pi@raspberrypi:~/uptime $ npm install
npm WARN package.json connect-flash@0.1.0 No README data
npm WARN package.json mongoose@3.6.7 bugs.email field must be a string email. Deleted.
|
> raw-socket@1.5.1 install /home/pi/uptime/node_modules/net-ping/node_modules/raw-socket
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 4.4.38-v7+
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pi/uptime/node_modules/net-ping/node_modules/raw-socket
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian                                                                   
 
npm ERR! raw-socket@1.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the raw-socket@1.5.1 install script.
npm ERR! This is most likely a problem with the raw-socket package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls raw-socket
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.4.38-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/uptime
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/uptime/npm-debug.log
npm ERR! not ok code 0

```

**Comment by ghost** [comment]
I think the problem is that you don't have Nodejs installed on your Raspberry Pi.

**Comment by andrija1987** [comment]
/bin/sh: 1: node: not found - here is your problem

Run below command, it will install nodejs for you.

Using Debian, as root
curl -sL https://deb.nodesource.com/setup_11.x | bash -
apt-get install -y nodejs
