### ISSUE TITLE
needingPoll endpoint responded with error code: 504

### ISSUE THREAD

**Issue by sharathshashidhar** [fzaninotto/uptime#362]
Hi,

Here's the error i am getting when i start the app in a linux machine.

Error: http://localhost:8082/api/checks/needingPoll resource responded with error code: 504
    at ClientRequest.<anonymous> (/home/uptime/lib/monitor.js:92:23)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:522:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at Socket.socketOnData (_http_client.js:411:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)

I have not added any proxy. 

>curl yahoo.com works as expected

I am trying to monitor internal sites. Can you please help?

Thanks & Regards
Sharath

**Comment by vijayk2019** [comment]
@sharathshashidhar Were you able to solve this issue? I am facing similar issue.
