### ISSUE TITLE
TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by flograsso** [fzaninotto/uptime#369]
I Have the following error when i execute "node app" coomand

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (C:\Users\SoporteSEM\Downloads\uptime-3.1\uptime-3.1\n
ode_modules\socket.io\lib\transports\websocket\hybi-07-12.js:442:43)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\SoporteSEM\Downloads\uptime-3.1\uptime-3.1\n
ode_modules\socket.io\lib\transports\websocket\index.js:7:6)
    at Module._compile (module.js:652:30)

**Comment by yanivsetton** [comment]
I also facing with this issue, any updates regarding this?

**Comment by keshrisohit** [comment]
i am also facing the same issue.

**Comment by almgwary** [comment]
same issue, you need to upgrade the project code for latest node and socket.io version

**Comment by yanivsetton** [comment]
make sure to install mongodb and websockio global, or if you can run this as a docker container 
curl -L https://github.com/IFSight/uptime/raw/master/run | sh
the docker-compose file is located under /usr/local/docker-uptime, this is the easiest method to get this running

**Comment by diveyez** [comment]
It needs to be hardcoded for patching this. Cannot be done without developmental procedures.

**Comment by Myzel394** [comment]
I'm also facing this issue 2,5 years later - any solution so far? Tried @yanivsetton but it didn't work.
